### ISSUE TITLE
Create an onloaded event that the sandbox will listen too

### ISSUE THREAD

**Issue by jaetask** [mauriciosoares/core.js#14]
Hi Mauricio,

Firstly, great work on the library so far. I have some ideas I would like to run past you, I will spend the day reading the source and running tests to get up to speed.

I have an idea where you would want to efficiently load modules in a specific order. This is one technique how the guardian.co.uk uses to get every page delivered under 1 second. They load the core modules first, even in plain html, so the user can read the content, then they load interesting things afterwards. SO it would be good to have an onloaded method called on the sandbox when a module has finished loading.

This would allow the chaining (grouping) of modules depending on importance like.

- Load static html modules.. logo, header, footer, news content etc.
- When completed. Load async interactive modules or libraries such as jquery, backbone, angular
- When completed. Load async library dependant modules

The point of this is to get the minimal content to the user fast. lightening fast. Then load the extra functionality one the user has something to read/do.

sudo code:

Core.register('header', function() {});
Core.register('footer', function() {});
Core.register('static-news', function() {});
Core.register('backbone', function() {});
Core.register('dynamic-news', function() {});

Core.start(['header','footer','static-news']).onComplete(function() {
Core.Start('backbone');
}).onComplete(function() {
Core.Start('dynamic-news');
});

What do you think? Would this be useful in the Core?

**Comment by mauriciosoares** [comment]
I see your point, and I totally agree in the way application are going to be build in the next years... And I think I can implement some cool features thinking about your idea, but probably I'll stick to the simple ones at first (since I don't have full time to work on core.js), but anyway, thank you for caring about core.js, it motivates me to keep working on it.

**Comment by jaetask** [comment]
+1 :)

**Comment by mauriciosoares** [comment]
I'll close this issue for now, but I'll keep it as a possible guide for future features.
