### ISSUE TITLE
document.getElementById

### ISSUE THREAD

**Issue by jaetask** [mauriciosoares/core.js#18]
Hi,

Just a quick note that this is almost 100% cross browser but jQuery reports that there are two potential issues. 

http://code.jquery.com/jquery-1.8.3.js

- Blackberry returns elements that are not in the dom
- Elements are returned if their name matches the id (Opera, IE.. versions unknown)

Thanks to http://stackoverflow.com/users/995876/esailija who reported it in this post. http://stackoverflow.com/questions/13830423/what-browsers-support-getelementbyid

**Comment by mauriciosoares** [comment]
Wow, that's something I didn't know about...

I'm gonna create a helper to verify those things.

Once its done I'll close this issue.

Thanks.

**Comment by kritollm** [comment]
Only check if element.id === id (if you recive a node reference), the blacburry issue probably never happens, maybe if you remove the element without removing the module.

**Comment by mauriciosoares** [comment]
Thanks @kritollm 

this check is really the easiest way to do it. I'll implement it right away and let you know.

The blackberry bug will have to wait a little bit... :)

**Comment by kritollm** [comment]
I thought it was hard to fix the Blackberry bug, but I took a quick look at jQuery and how they solved the Blackberry bug. Just check if the item has a parent element. Like this:

I thought it was hard, but took a quick look at jQuery and Blackberry bug was easy to fix. Just check if the item has a parent element.

Core.prototype.var getElement = function(id) {
    var el =document.getElementById(id);
   return el.id === id && el.parentElement ? el : null;
};

**Comment by mauriciosoares** [comment]
Yup, that's good.

Thanks for the help @kritollm and @jaetask.
