### ISSUE TITLE
create a simple template system

### ISSUE THREAD

**Issue by mauriciosoares** [mauriciosoares/core.js#29]
Today if the the module has the same ID of an element in the DOM, it automatically get's a reference of this element using `this.el`.

It would be nice to Core.js recognise if that id is from an template, and then in the `this.el` would be a function that would accept an Object with the values from that template. And once executed returns the html string of that template.

For that I could make use of the micro templating system created by John Resig in this [link](http://ejohn.org/blog/javascript-micro-templating/)

**Comment by jaetask** [comment]
I would be careful of assuming thing like this. Its starting to look a little tightly coupled to the dom.

**Comment by hwclass** [comment]
I agree with jaetask; the main purpose of Core.js needs to be kept to stay as decoupled.

**Comment by mauriciosoares** [comment]
Thanks for your reply, after I opened this issue I got myself thinking about that as well...

But the thing is that you don't have to use the `this.el` at all, but since most of your modules are probably going to be a part of your app in the DOM, I think it's helpful to have a reference automatically in the module.

As the docs says, if there's no element in the DOM with the same ID of the module, then `this.el` will point to `null` and you won't have any problem with that.

What do you guys think about that?

**Comment by jaetask** [comment]
I have found that whenever 'magic' happens, it always causes problems later. I prefer to be explicit. If I want that they I just pass it as a config option. there will always be a case where there is a dom element on a page that just happens to be the same as your module and then you get into trouble. Especially when you are working on sites that allow 3rd parties to inject html, such as in advertising campaigns.

**Comment by mauriciosoares** [comment]
I get it, and probably the template is a little to much to core.js indeed, I'll stick to the `this.el` for now by having an element in the DOM with the same ID as the module name, and try to think in a more elegant solution for it later.

Thanks @jaetask and @hwclass.
