### ISSUE TITLE
Notify, no way to listen to all events and event message is lost on listen

### ISSUE THREAD

**Issue by jaetask** [mauriciosoares/core.js#31]
I have been playing with the message bus and want to show a possible problem. If you want to have a logging class or something to listen to all messages then the message is lost if you assign the same function to the listener.

e.g.

```
sandbox.listen('page-header-loaded', this.log, this);
sandbox.listen('advert-loaded', this.log, this);
log: function(data) {
   // Which event was fired? No way to know..
   console.log(data);
}
```

See this gist
https://gist.github.com/jaetask/4bd15608a8c0931be0b7

**Comment by jaetask** [comment]
I wonder if it would be better to pass the whole object to the listener and not need to specify a type.

something like this:
```
sandbox.notify('message-name', {some: 'value'});
log: function(event, data) {}
```

This simplifies the event API and also allows for a possible 3 param version when message channels are added (like in backbone marionette) When there are lots of events on a page, we really dont want everything listening to them. so we could do this.
```
sandbox.notify('channel-name', 'message-name', {some: 'value'});
sandbox.listen('channel-name', 'all', this.log, this);
log: function(event, data) {}
```

**Comment by mauriciosoares** [comment]
Hey, I can easily implement it that way, and I agree that it is helpful to know from which notifier the notification came from.

One question, when you said `all` in the last example, you mean that there's a notification called "all"? or if I put "all" then I want to listen to all notifications from all modules?

**Comment by jaetask** [comment]
Great :)

Yes, all means the same as *, so listen to all notifications. This is how backbone works and its very useful

**Comment by mauriciosoares** [comment]
Cool, I'll treat that `all` as `*` like you said.

I'll keep this issue opened as I work on that. Thanks

**Comment by jaetask** [comment]
How would you feel about integrating with another small library? or enabling channelled eventing through a plugin? 

Would it be possible to make the sandbox event into a pluggable thing? allowing something like mediator.js to be used.

http://thejacklawson.com/Mediator.js/

**Comment by mauriciosoares** [comment]
I think your point is good, but I didn't want to include any external libs for now...

But as things gets more complex, I'll consider it. :D

**Comment by jaetask** [comment]
Actually, I totally agree. Keep it simple, keep it internal. The messaging will be more than good enough for now and when channeling is required we can look at it proper. There are more important issues to focus on.

100% agree :+1:

**Comment by allain** [comment]
Passing around the module is probably not a great idea: https://www.youtube.com/watch?v=b5pFv9NB9fs at 19:15 basically warns against it explicitly. It will lead to increased coupling between the modules composing the app.

**Comment by jaetask** [comment]
Hi @allain, I don't understand the last comment. We are not discussing passing the module around. This thread is about changing the notify messages to also include the message name, so that when we enable a `sandbox.listen('*')` ability the function that is assigned will know which message was sent wit the data payload.

Hope that helps clarify.

**Comment by allain** [comment]
Indeed. There was a previous comment about passing the whole object around threw me. I misread. Sorry

**Comment by GrosSacASac** [comment]
good suggestion, especially for debugging and maintenance

**Comment by GrosSacASac** [comment]
Having a message name and channel name is redundant
`sandbox.notify('channel-name', 'message-name', {some: 'value'});`

Propagating a context is also redundant, there are many ways to do it already, apply, bind, call, closures arrow functions ...
`listening.callback.call(listening.context, notification.data);`

Two things should be added:
 * A way to listen to everything
 * The type of the event should be provided to the listener functions

This should solve all use cases.

We should also re-consider if it is worth using https://github.com/ajacksified/Mediator.js or https://github.com/GrosSacASac/event-e3 in the future

**Comment by GrosSacASac** [comment]
Have a look at https://github.com/mauriciosoares/core.js/blob/architecture-change/examples/simple/main.js#L28

**Comment by GrosSacASac** [comment]
only the main file (the one that imports core) has the possiblity to listen on ALL, as I consider it out of scope for individual modules
