### ISSUE TITLE
Stop multiple modules on Core.stop

### ISSUE THREAD

**Issue by mauriciosoares** [mauriciosoares/core.js#38]
`Core.stop` should accept an array of multiple modules:

``` js
Core.stop(['module1', 'module2', 'module3']);
```

**Comment by GrosSacASac** [comment]
This would be a displacement of complexity in best case, worst case added complexity. This is good enough
```
Core.stop('module1');
Core.stop('module2');
Core.stop('module3');
```
or

```
['module1', 'module2', 'module3'].forEach(function (moduleName) {
    Core.stop('module1');
});
```

https://en.wikipedia.org/wiki/Kolmogorov_complexity
https://en.wikipedia.org/wiki/Feature_creep
