### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by mauriciosoares** [mauriciosoares/core.js#40]
there's already a popular project named core.js: https://github.com/zloirock/core-js

I should think of a new name... that's hard!

**Comment by hwclass** [comment]
Some advices : box.js, craft.js, root.js, decouple.js, final.js, and some.js.

**Comment by mauriciosoares** [comment]
Thanks @hwclass!

I'm glad there's someone still watching this repository, It's being a long time since I don't work here...

I'll check if they're available. :)

**Comment by igorapa** [comment]
gangue.js, ibiuna.js, aaaaaahhh.js, deus.js, maizena.js.

**Comment by mauriciosoares** [comment]
Hey guys, what you think about `eroc.js` ?

It's core backwards... Definitely all the good names are taken :/ 

@igorapa @hwclass

**Comment by augustoabreu** [comment]
Since everything is a module, why not modular.js?

**Comment by GrosSacASac** [comment]
closing for now, re-open if you feel there is a real need to change the name
