### ISSUE TITLE
Status of project ?

### ISSUE THREAD

**Issue by GrosSacASac** [mauriciosoares/core.js#53]
Hi I am interested in evolving this project, 

Some questions:

What is the status of project ? Paused ? or Stopped ?

For all watchers:

How are you using this project ?
If you are not, what are you using instead and why ?
What features are missing ?

It would be nice if I could get Contributor status to make branches in place, avoiding fork.

**Comment by mauriciosoares** [comment]
Hey @GrosSacASac :)

The status of the project is pretty much stopped 😞... I worked on this a couple of years ago as a learning project, it ended up being quite decent, but with a lot of recent technologies, I don't think it would be wise to use it in production...

I've been working a lot with react and redux nowadays, and I think that this combination solves many (if not all) of the problems I tried to solve with core.js more elegantly and performant. Of course there are tons of other alternatives that have a bunch of contributors and support from the community, so you'll definitely have other options as well.

But in case you want to keep this project alive, and use it in your own projects, I would gladly give you a contributor status, so you can work on it 🙂

**Comment by GrosSacASac** [comment]
Yes, please :)

I also worked with redux. I think core js has some really good concepts, some hidden as well (not seen in presentation), that I want to leverage and develop further.

Some stuff is outdated/not needed anymore and could be updated as well

**Comment by mauriciosoares** [comment]
Awesome, I'm glad you're interested on maintaining the project, I can give you full support in terms of how things were done in the past (if I remember of course hahaha), but unfortunately I cannot promise you that I'll be contributing to it in terms of code. But I'll be more then happy to review your pull requests :)
