### ISSUE TITLE
Publishing the project

### ISSUE THREAD

**Issue by GrosSacASac** [mauriciosoares/core.js#55]
Should we continue to use bower ?

Should we publish on npm ?

**Comment by mauriciosoares** [comment]
IMO we can drop bower, and just support npm.

maybe even add it to a public cdn like cdnjs or something similar

**Comment by GrosSacASac** [comment]
https://docs.npmjs.com/misc/scope

Should we publish on npm as bare , or as scoped package ?

Scope would allow us to later publish other packages under the same umbrella.
It also allows us to take a name that is already taken as bare publish.


I propose to publish as `@core/core` dropping `.js` as it is technically not limited to js.

**Comment by GrosSacASac** [comment]
for public cdn https://unpkg.com/ is also a possiblity

**Comment by GrosSacASac** [comment]
https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist
cdnjs is not inclusive to all and does not support latest version

**Comment by mauriciosoares** [comment]
well, to make things simpler, I'd only publish on npm then... at least for the initial release. We can use cdn's in case other users request it

About the naming, it's really up to your personal preference... if @core is available, that would be interesting, I also don't like the `.js` in the package name

**Comment by GrosSacASac** [comment]
@core is not available, what about @eroc ?
That would make a @eroc/core package

**Comment by mauriciosoares** [comment]
sounds good :)

Small and easy to remember 💃

**Comment by GrosSacASac** [comment]
OK, I already created eroc org, ask me if you want to be added as well. I will proceed with https://bower.io/blog/2017/how-to-drop-bower-support/ and publishing to npm

**Comment by GrosSacASac** [comment]
Published https://www.npmjs.com/package/@eroc/core
