### ISSUE TITLE
Add another simple example

### ISSUE THREAD

**Issue by GrosSacASac** [mauriciosoares/core.js#71]
Tick tack toe game, todo list, quizz etc.

What is your simplest web project ? Try to convert it to use the core concept and add it in the examples.

**Comment by navneetsharmaui** [comment]
@GrosSacASac I would Like to implement the TicTacToe game. for core.js

**Comment by navneetsharmaui** [comment]
Can you assign me this?

**Comment by GrosSacASac** [comment]
Go ahead, and don't hesitate to ask questions along the way

**Comment by jrhorn424** [comment]
If you'd like help with these examples, whether it's code review, collaborative writing, or advice on pedagogy, I'd like to help.

**Comment by GrosSacASac** [comment]
feel free to add more examples

**Comment by GrosSacASac** [comment]
Added example/draw, try it out !
I am closing this issue as solved but feel free to add more
