### ISSUE TITLE
Feature request: Use workers to split up modules.

### ISSUE THREAD

**Issue by MyIsaak** [mauriciosoares/core.js#90]
Since the architecture of this framework splits things into modules that only communicate with each other via events messaging, couldn't we add an options to use workers mode instead since it also follows the same paradigm? A downside I can see already would be DOM access but I think it still offers a nice structure, instead of creating a worker module inside a module.

**Comment by GrosSacASac** [comment]
Good idea

**Comment by GrosSacASac** [comment]
Thinking

- Ideally modules should be written in the same way (export start stop)
- It would be nice to have a single toggle  when using core.start like `core.start(moduleA,  {worker: true})`
- Web Worker require an url (or equivalent) in the constructor
- Glue code needs to be injected at some point, to be able to call start, and patch the event emitter
- Whenever we emit an event we need to loop through all active modules in workers
- Whenever a module in a worker emits a message we don't, and instead we send a message to core that emits (patch this also in glue code)

I will try something

**Comment by MyIsaak** [comment]
> Ideally modules should be written in the same way (export start stop)

Having `.stop()` would be great because by default there aren't any destructor methods on Workers by default. It has been [removed for some reason.](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/onclose)

> It would be nice to have a single toggle when using core.start like core.start(moduleA, {worker: true})

Agreed. The syntax should be minimal.

> Web Worker require an url (or equivalent) in the constructor

Check out: https://github.com/mohayonao/inline-worker/blob/7014cd64c3cd6eb884f6743aad682a995e262bb9/index.js#L10-L16

> Glue code needs to be injected at some point, to be able to call start, and patch the event emitter
> Whenever a module in a worker emits a message we don't, and instead we send a message to core that emits (patch this also in glue code)

A glue code injected inside the worker which:
- calls `start(emitter)` where `emitter` is `self`
- patch `self` with wrappers functions for `.emit(name, data) -> postMessage({name, data})` and `.on(name, fn) -> .addEventListener(name, fn)`
- propagate events from `onmessage({name, data})` to the right event via `.dispatchEvent(CustomEvent(name, {detail: data}))`
- bubbles events (worker to parent) from `emit(name, data)`to `postMessage({name, data})`

> Whenever we emit an event we need to loop through all active modules in workers

Sounds like a good idea.

**Comment by MyIsaak** [comment]
What also to consider is passing ownership when dispatching events to support passing ArrayBuffers, OffscreenCanvas, etc.. Perhaps one of these 2 signatures could be used: `.emit(name, data, transfer)` or `.emitAndTransfer(name, data, transfer)`

**Comment by GrosSacASac** [comment]
https://github.com/mauriciosoares/core.js/pull/91

**Comment by GrosSacASac** [comment]
Please try 4.1.0, opened new follow up issues

**Comment by GrosSacASac** [comment]
I ended up not dispatching events on self directly, to be able to distinguish commands (start, stop, getState) from regular events
